### PR TITLE
Update README file to Markdown 📃

### PR DESCRIPTION
**Pull request by joaoofreitas**
Since the README file of this repository was 5 years old. I took the initiative of creating this update in formatting using markdown. If you need anything else please respond to this pull request so I can change it. 

Leave your thoughts below about this change.
I would appreciate it if my pull request is accepted since this is my first contribution to [_golang_](https://golang.org/). I would certainly like to contribute more.

Best Regards

### CODE REVIEW

**Comment by joaoofreitas** [comment]
@googlebot I signed it!

**Comment by joaoofreitas** [comment]
@stapelberg Can you check this please?

**Comment by stapelberg** [comment]
I’m only the most recent contributor, I have no write access to this repository either.

I don’t know if the README can be modified safely, or if this change will be overwritten on the next sync, sorry.

**Comment by joaoofreitas** [comment]
> I’m only the most recent contributor, I have no write access to this repository either.
> 
> I don’t know if the README can be modified safely, or if this change will be overwritten on the next sync, sorry.

Can you tag someone who has write access to this repository?
Thank you so far.

**Comment by stapelberg** [comment]
I don’t know off-hand. I can try to find out next week.

**Comment by robpike** [comment]
Thanks for this. I think it's fine to merge.

**Pull request merged**
