### PR TITLE
Run gofmt -s -w

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by zombiezen** [comment]
@lmmilewski

**Comment by LMMilewski** [comment]
Please see the README. This project does not accept pull requests.

**Comment by SmaugTheGreat** [comment]
This project violates so many go-policies, it should be deleted.

**Comment by phuslu** [comment]
glog has a nice interface and good performance.

It's a pity it lacks some _modern_ features, so I forked glog then added two features,
- daily rolling  (composite glog file togather and rotating by time, without no overhead)
- json formatter logging (algin to zerolog/zap, performance is same as glog baseline)

https://github.com/phuslu/glog (comments and review is welcome)

**Pull request closed without merging**
